include ../Makefile.env

TARGET = capture2file

SRCS = 
SRCS += main.c
SRCS += ../common/util_v4l2.c
SRCS += ../common/util_drm.c

OBJS =
OBJS += $(SRCS:%.c=./%.o)

INCLUDES += -I../common/

CFLAGS   +=

LDFLAGS  +=

include ../Makefile.include
